"""adiciona responsavel_nome em movimentacoes

Revision ID: a9f2e49732df
Revises: 4dad2c615fdf
Create Date: 2026-08-05 21:42:49.965234

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a9f2e49732df'
down_revision: Union[str, Sequence[str], None] = '4dad2c615fdf'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('movimentacoes', sa.Column('responsavel_nome', sa.String(length=150), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('movimentacoes', 'responsavel_nome')
    # ### end Alembic commands ###
